rvm:
  - 1.8.7
  - 1.9.2
  - ree
  - ruby-head
notifications:
  # overriding this so billing@teamsporttech.com (who owns the repo) doesn't get spammed
  # anyone, feel free to add yourselves
  email:
    - patrick.byrne@tstmedia.com
    - jon.karna@tstmedia.com
